name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - dev

env:
  NODE_VERSION: 18.14.2

jobs:
  test-and-upload-migration-files-for-check:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test?sslmode=disable
      PGSSL: disable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run formatting tests
        run: |
          ls -la
          npm run test:formatting
          wait

      - name: Seed the service database with the current schema
        run: |
          rm -rf migrations
          npx drizzle-kit generate --config=drizzle.config.ts
          npm run DB:applyMigration

      - name: Setup and check migrations
        run: |
          npm run DB:createNewMigration
          npm run DB:checkMigration

      - name: Upload migrations folder
        uses: actions/upload-artifact@v4
        with:
          name: migrations
          path: ./migrations
          retention-days: 1
